version: '3.8'

services:
  xiaozhiclient-test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: xiaozhiclient-test:0.1
    container_name: xiaozhiclient-test
    ports:
      - "8090:8090"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8090
    volumes:
      # 可选：挂载日志目录
      - ./logs:/var/log/nginx
    networks:
      - xiaozhi-network

networks:
  xiaozhi-network:
    driver: bridge 