# Docker安装Server

version: '3'
services:
  fudian-ai-server:
    image: ghcr.nju.edu.cn/xinnan-tech/fudian-ai-server:server_latest
    container_name: fudian-ai-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports:
      # ws服务端
      - "8000:8000"
      # http服务的端口，用于简单OTA接口(单服务部署)，以及视觉分析接口
      - "8003:8003"
    volumes:
      # 配置文件目录
      - ./data:/opt/fudian-ai-server/data
      # 模型文件挂接，很重要
      - ./models/SenseVoiceSmall/model.pt:/opt/fudian-ai-server/models/SenseVoiceSmall/model.pt